### ISSUE TITLE
Task `generateOpenApiClient` cannot  be executed in example project

### ISSUE THREAD

**Issue by OptimumCode** [nomisRev/OpenAPI-kt#28]
Hi,

After cloning the project and trying to execute `generateOpenApiClient` task in the example project I got the following error:

<details>
<summary>./gradlew clean build --console plain generateOpenApiClient --stacktrace</summary>

```text
Type-safe project accessors is an incubating feature.
> Task :cleanJvmTest UP-TO-DATE
> Task :cleanAllTests UP-TO-DATE
> Task :clean
> Task :generateProjectStructureMetadata
> Task :allMetadataJar
> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :compileKotlinJvm NO-SOURCE
> Task :jvmProcessResources NO-SOURCE
> Task :jvmMainClasses UP-TO-DATE
> Task :jvmJar
> Task :assemble
> Task :compileTestKotlinJvm NO-SOURCE
> Task :jvmTestProcessResources NO-SOURCE
> Task :jvmTestClasses UP-TO-DATE
> Task :jvmTest NO-SOURCE
> Task :allTests NO-SOURCE
> Task :check UP-TO-DATE
> Task :build
> Task :generateOpenApiClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateOpenApiClient'.
> io/github/nomisrev/openapi/MainKt

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateOpenApiClient'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:148)
...
Caused by: java.lang.NoClassDefFoundError: io/github/nomisrev/openapi/MainKt
        at io.github.nomisrev.openapi.plugin.GenerateClientTask.sampleAction(GenerateClientTask.kt:37)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
...
Caused by: java.lang.ClassNotFoundException: io.github.nomisrev.openapi.MainKt
        at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
        ... 121 more
```
</details>

The interesting part is that the error was gone once I executed the `publishToMavenLocal` task for the main Gradle project and retried to generate the OpenApi client. I am still trying to figure out the reason for that but, most likely, it is somehow related to publications metadata.

The only thing I have managed to determine is that plugin's dependencies when published locally or loaded from the Gradle portal are different. Here are parts of `buildEnvironment` task's output for the example project for both cases:

<details>
<summary>Published locally</summary>

```text
+--- io.github.nomisrev.openapi.plugin:io.github.nomisrev.openapi.plugin.gradle.plugin:1.0.0
|    \--- io.github.nomisrev.openapi:gradle-plugin:1.0.0
|         +--- org.jetbrains.kotlin:kotlin-stdlib:2.0.20-Beta1 -> 1.9.20 (*)
|         +--- org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.20-Beta1 (*)
|         \--- io.github.nomisrev:openapi-kt-generator:0.0.1
|              +--- com.squareup.okio:okio:3.9.0
|              +--- io.ktor:ktor-client-core:2.3.12
|              +--- io.github.nomisrev:openapi-kt-typed:0.0.1
|              |    \--- io.github.nomisrev:openapi-kt-typed-jvm:0.0.1
|              |         +--- io.github.nomisrev:openapi-kt-parser:0.0.1
|              |         |    \--- io.github.nomisrev:openapi-kt-parser-jvm:0.0.1
|              +--- net.pearx.kasechange:kasechange:1.4.1
|              |    \--- net.pearx.kasechange:kasechange-jvm:1.4.1
|              +--- com.squareup:kotlinpoet:1.17.0
|              |    \--- com.squareup:kotlinpoet-jvm:1.17.0
|              \--- org.jetbrains.kotlin:kotlin-stdlib:2.0.20-Beta1 -> 1.9.20 (*)
```
</details>

<details>
<summary>From Gradle portal</summary>

```text
+--- io.github.nomisrev.openapi.plugin:io.github.nomisrev.openapi.plugin.gradle.plugin:1.0.0
|    \--- io.github.nomisrev.openapi:gradle-plugin:1.0.0
|         +--- org.jetbrains.kotlin:kotlin-stdlib:2.0.20-Beta1 -> 1.9.20 (*)
|         +--- org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.20-Beta1 (*)
|         \--- io.github.nomisrev:openapi-kt-generator:0.0.1
|              \--- io.github.nomisrev:openapi-kt-generator-jvm:0.0.1
|                   +--- io.github.nomisrev:openapi-kt-parser:0.0.1
|                   |    \--- io.github.nomisrev:openapi-kt-parser-jvm:0.0.1
|                   \--- org.jetbrains.kotlin:kotlin-stdlib:2.0.20-Beta1 -> 1.9.20 (*)
```
</details>

If I find more details I will let you know.

**Comment by OptimumCode** [comment]
Probably, this is the reason:

Neither [POM](https://repo1.maven.org/maven2/io/github/nomisrev/openapi-kt-generator/0.0.1/openapi-kt-generator-0.0.1.pom) nor [Gradle module](https://repo1.maven.org/maven2/io/github/nomisrev/openapi-kt-generator/0.0.1/openapi-kt-generator-0.0.1.module) files contain dependencies to:

- com.squareup.okio:okio
- com.squareup:kotlinpoet
- net.pearx.kasechange:kasechange

And most likely, the reason for `Caused by: java.lang.ClassNotFoundException: io.github.nomisrev.openapi.MainKt` is an exception during class loading due to missing dependencies it imports.

**Comment by OptimumCode** [comment]
And maybe this is the reason why POM and Gradle module have incorrect dependencies:
```text
> Task :typed:publishKotlinMultiplatformPublicationToMavenCentralRepository
Multiple publications with coordinates 'io.github.nomisrev:openapi-kt-generator:0.0.1' are published to repository 'mavenCentral'. The publications 'kotlinMultiplatform' in project ':typed' and 'maven' in project ':generation' will overwrite each other!
```

Those are logs from this [run](https://github.com/nomisRev/OpenAPI-kt/actions/runs/9624349523/job/26549764989).

**Comment by OptimumCode** [comment]
And looks like you already fixed the reason for that here https://github.com/nomisRev/OpenAPI-kt/commit/24f4a22cbafe932b1e091d2a723fd24248da52a8))

**Comment by nomisRev** [comment]
Hey @OptimumCode,

Thank you for taking an interest in this project! ☺️

I'm actually not sure what is going on here, it seems that there is a difference between publishing to MavenCentral and Gradle Portal. Make matters even stranger, it's not working for with `publishToMavenLocal` anymore and I think I published an incorrect plugin to Gradle Portal since I hadn't setup an account there yet? 😕 🤕

**Comment by OptimumCode** [comment]
>  it's not working for with publishToMavenLocal anymore

Hm...this is very strange - maybe you should try to remove artifacts from your maven local and retry?

> I think I published an incorrect plugin to Gradle Portal since I hadn't setup an account there yet?

But it resolves the plugin somehow (gradle scan shows the plugin was resolved from Gradle Portal)... But probably, you are right here. If you don't have an account on Gradle Portal you cannot publish a plugin there. And I cannot find the plugin on [Gradle Portal by id](https://plugins.gradle.org/search?term=io.github.nomisrev.openapi.plugin).

**Comment by nomisRev** [comment]
This is fixed ☺️ Currently still release on `mavenCentral` to be available for plugin resolution, that needs to be added to the README still.
